import { v4 as uuidv4 } from 'uuid';

const healthCheckController = require('./controllers/health-check.controller');
const chatController = require('./controllers/chat.controller');
const adminController = require('./controllers/admin.controller');

export function initializeControllers(app) {
    app.get('/healthcheck',
        /* 
          #swagger.tags = ['Health Check']
          #swagger.summary = 'Health Check'
          #swagger.description = 'Perform a health check'
        */
        healthCheckController.get);

    app.post('/chat/:uuid',
        /* 
            #swagger.tags = ['Chat']
            #swagger.summary = 'Chat using KB articles'
            #swagger.description = 'Chat with AI using KB articles'
            #swagger.parameters['uuid'] = {
              in: 'path',
              description: 'UUID of support channel kb',
              required: true,
              type: 'string'
            }
            #swagger.parameters['query'] = {
              in: 'body',
              description: 'KbCollection payload',
              required: true,
              schema: {
                  query: "query text"
              }
          }
        */
        chatController.post);

    app.get('/admin',
        /* 
            #swagger.tags = ['Admin']
            #swagger.summary = 'Get admin chat setting'
            #swagger.description = 'Get admin chat setting'
          }
        */
        adminController.get);
    
    app.post('/admin',
        /* 
            #swagger.tags = ['Admin']
            #swagger.summary = 'Add admin chat setting'
            #swagger.description = 'Add admin chat setting'
            #swagger.parameters['body'] = {
              in: 'body',
              description: 'Channel Config',
              required: true,
              schema: {
                  uuid: "Leave empty, will be generated by api",
                  system_prompt: "The system prompt for the support channel",
                  model: "OpenAI model to use",
                  max_tokens: 150,
                  temperature: 0.7,
                  max_context_length: 4000,
                  kbs: [],
                  name: "The name of this support channel"
              }
          }
        */
        adminController.post);

    app.put('/admin/:uuid',
        /* 
			#swagger.tags = ['Admin']
			#swagger.summary = 'Update Channel settings'
			#swagger.description = 'Update Channel settings'
	
			#swagger.parameters['uuid'] = {
				in: 'path',
				description: 'UUID of the support channel',
				required: true,
				type: 'string'
			}
	
			#swagger.parameters['body'] = {
				in: 'body',
				description: 'Updated chat settings',
				required: true,
				schema: {
					system_prompt: "The updated system prompt for the support channel",
					model: "Updated OpenAI model to use",
					max_tokens: 200,
					temperature: 0.8,
					max_context_length: 5000,
					kbs: [],
					name: "The updated name of this support channel"
				}
			}
		*/
        adminController.put);

    app.delete('/admin/:uuid',
        /* 
            #swagger.tags = ['Admin']
            #swagger.summary = 'Delete admin chat setting'
            #swagger.description = 'Delete admin chat setting'
            #swagger.parameters['uuid'] = {
              in: 'path',
              description: 'UUID of the setting value to delete',
              required: true,
              type: 'string'
            } 
          }
        */
        adminController.delete);
}

export function connectionIdMiddleware(req, res, next) {
    // Check if connectionId exists in headers or cookies
    let connectionId = req.cookies?.connectionId;

    // If no connectionId, generate a new one
    if (!connectionId) {
        connectionId = uuidv4();

        res.cookie('connectionId', connectionId, {
            httpOnly: true,
            secure: true,
            sameSite: 'none',
            maxAge: 30 * 24 * 60 * 60 * 1000 // Optional: 30 days expiry
        });
    }

    // Attach to request for downstream use
    req.connectionId = connectionId;
    next();
}
